import type { KeyResponse } from "./response";

/**
 * Uses `KeyboardEvent.code` as key
 */
export default interface KeyboardLayout {
  Backspace: KeyResponse;
  Tab: KeyResponse;
  Space: KeyResponse;
  ArrowLeft: KeyResponse;
  ArrowUp: KeyResponse;
  ArrowRight: KeyResponse;
  ArrowDown: KeyResponse;
  Digit0: KeyResponse;
  Digit1: KeyResponse;
  Digit2: KeyResponse;
  Digit3: KeyResponse;
  Digit4: KeyResponse;
  Digit5: KeyResponse;
  Digit6: KeyResponse;
  Digit7: KeyResponse;
  Digit8: KeyResponse;
  Digit9: KeyResponse;
  KeyA: KeyResponse;
  KeyB: KeyResponse;
  KeyC: KeyResponse;
  KeyD: KeyResponse;
  KeyE: KeyResponse;
  KeyF: KeyResponse;
  KeyG: KeyResponse;
  KeyH: KeyResponse;
  KeyI: KeyResponse;
  KeyJ: KeyResponse;
  KeyK: KeyResponse;
  KeyL: KeyResponse;
  KeyM: KeyResponse;
  KeyN: KeyResponse;
  KeyO: KeyResponse;
  KeyP: KeyResponse;
  KeyQ: KeyResponse;
  KeyR: KeyResponse;
  KeyS: KeyResponse;
  KeyT: KeyResponse;
  KeyU: KeyResponse;
  KeyV: KeyResponse;
  KeyW: KeyResponse;
  KeyX: KeyResponse;
  KeyY: KeyResponse;
  KeyZ: KeyResponse;
  Numpad0: KeyResponse;
  Numpad1: KeyResponse;
  Numpad2: KeyResponse;
  Numpad3: KeyResponse;
  Numpad4: KeyResponse;
  Numpad5: KeyResponse;
  Numpad6: KeyResponse;
  Numpad7: KeyResponse;
  Numpad8: KeyResponse;
  Numpad9: KeyResponse;
  NumpadMultiply: KeyResponse;
  NumpadAdd: KeyResponse;
  NumpadSubtract: KeyResponse;
  NumpadDecimal: KeyResponse;
  NumpadDivide: KeyResponse;
  Semicolon: KeyResponse;
  Equal: KeyResponse;
  Comma: KeyResponse;
  Minus: KeyResponse;
  Period: KeyResponse;
  Slash: KeyResponse;
  Backquote: KeyResponse;
  BracketLeft: KeyResponse;
  Backslash: KeyResponse;
  BracketRight: KeyResponse;
  Quote: KeyResponse;
}
