import type { GegeeKeyResponse } from "./response";

/**
 * Uses `KeyboardEvent.code` as key
 */
export default interface GegeeKeyboardLayout {
  Space: GegeeKeyResponse;
  ArrowLeft: GegeeKeyResponse;
  ArrowUp: GegeeKeyResponse;
  ArrowRight: GegeeKeyResponse;
  ArrowDown: GegeeKeyResponse;
  Digit0: GegeeKeyResponse;
  Digit1: GegeeKeyResponse;
  Digit2: GegeeKeyResponse;
  Digit3: GegeeKeyResponse;
  Digit4: GegeeKeyResponse;
  Digit5: GegeeKeyResponse;
  Digit6: GegeeKeyResponse;
  Digit7: GegeeKeyResponse;
  Digit8: GegeeKeyResponse;
  Digit9: GegeeKeyResponse;
  KeyA: GegeeKeyResponse;
  KeyB: GegeeKeyResponse;
  KeyC: GegeeKeyResponse;
  KeyD: GegeeKeyResponse;
  KeyE: GegeeKeyResponse;
  KeyF: GegeeKeyResponse;
  KeyG: GegeeKeyResponse;
  KeyH: GegeeKeyResponse;
  KeyI: GegeeKeyResponse;
  KeyJ: GegeeKeyResponse;
  KeyK: GegeeKeyResponse;
  KeyL: GegeeKeyResponse;
  KeyM: GegeeKeyResponse;
  KeyN: GegeeKeyResponse;
  KeyO: GegeeKeyResponse;
  KeyP: GegeeKeyResponse;
  KeyQ: GegeeKeyResponse;
  KeyR: GegeeKeyResponse;
  KeyS: GegeeKeyResponse;
  KeyT: GegeeKeyResponse;
  KeyU: GegeeKeyResponse;
  KeyV: GegeeKeyResponse;
  KeyW: GegeeKeyResponse;
  KeyX: GegeeKeyResponse;
  KeyY: GegeeKeyResponse;
  KeyZ: GegeeKeyResponse;
  Numpad0: GegeeKeyResponse;
  Numpad1: GegeeKeyResponse;
  Numpad2: GegeeKeyResponse;
  Numpad3: GegeeKeyResponse;
  Numpad4: GegeeKeyResponse;
  Numpad5: GegeeKeyResponse;
  Numpad6: GegeeKeyResponse;
  Numpad7: GegeeKeyResponse;
  Numpad8: GegeeKeyResponse;
  Numpad9: GegeeKeyResponse;
  NumpadMultiply: GegeeKeyResponse;
  NumpadAdd: GegeeKeyResponse;
  NumpadSubtract: GegeeKeyResponse;
  NumpadDecimal: GegeeKeyResponse;
  NumpadDivide: GegeeKeyResponse;
  Semicolon: GegeeKeyResponse;
  Equal: GegeeKeyResponse;
  Comma: GegeeKeyResponse;
  Minus: GegeeKeyResponse;
  Period: GegeeKeyResponse;
  Slash: GegeeKeyResponse;
  Backquote: GegeeKeyResponse;
  BracketLeft: GegeeKeyResponse;
  Backslash: GegeeKeyResponse;
  BracketRight: GegeeKeyResponse;
  Quote: GegeeKeyResponse;
}
